name: Env_RESHUFFLE
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python==3.8
  - pytorch::pytorch==2.1.0
  - nvidia::cudatoolkit==11.5.0
  - pip
  - pip:
      - pykeen==1.10.1
      - numpy<2.0
      - class_resolver==0.4.3
      - tensorboard==2.14.0
